export const ERROR_CODES = {
  AUTH: {
    USER_ALREADY_EXISTS: 'A01',
    INVALID_PASSWORD: 'A02',
    UN_AUTHORIZED: 'A03',
  },
  GAME: {
    GAME_NOT_FOUND: 'G01',
    INVALID_GAME_STATUS: 'G02',
    INVALID_GAME_ID: 'G03',
  },
  QUESTION: {
    QUESTION_NOT_FOUND: 'Q01',
    INVALID_QUESTION_ID: 'Q02',
    QUESTION_LIMIT_EXCEEDED: 'Q03',
    QUESTION_TEXT_ANSWER_REQUIRED: 'Q04',
  },
  ROOM: {
    ROOM_NOT_FOUND: 'R01',
    INVALID_ROOM_ID: 'R02',
    ROOM_CANNOT_BE_UPDATED: 'R03',
    ROOM_CANNOT_BE_DELETED: 'R04',
  },
};
